import type { Metadata } from "next";
import { Yuji_Syuku, Outfit } from "next/font/google";
import "./globals.css";

const yujiSyuku = Yuji_Syuku({
  weight: "400",
  variable: "--font-yuji-syuku",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${yujiSyuku.variable} ${outfit.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
